import type { SiteConfig } from "./siteTypes";

export const defaultConfig: SiteConfig = {
  brand: {
    name: "Ignacio de las Rivas",
    tagline: "Fotografía Inmobiliaria Premium",
    primaryColor: "#C15B3A",
    bgColor: "#F5F1EC",
    darkColor: "#1C1714",
    phone: "601408966",
    email: "info@ignaciodelasfotografia.es",
    location: "Madrid · Disponible en toda España",
    instagram: "@ignaciodelasfotografia",
    whatsapp: "34601408966",
    city: "Madrid",
  },
  navbar: {
    brandName: "Ignacio de las Rivas",
    links: [
      { href: "#servicios", label: "Servicios" },
      { href: "#portfolio", label: "Portfolio" },
      { href: "#proceso", label: "Proceso" },
      { href: "#testimonios", label: "Testimonios" },
      { href: "#contacto", label: "Contacto" },
    ],
    ctaText: "Solicitar Presupuesto",
    primaryColor: "#C15B3A",
  },
  hero: {
    badge: "Fotografía Inmobiliaria Premium · Madrid",
    headline: "Fotografías que",
    accentWord: "venden",
    headlineAccent: "antes y mejor.",
    subheadline:
      "Fotografía profesional de interiores y viviendas en Madrid. Imágenes de alta calidad que destacan tu propiedad en Idealista, Fotocasa y cualquier portal inmobiliario.",
    ctaPrimary: "Solicitar Sesión",
    ctaSecondary: "Ver Portfolio",
    trustText: "+127 clientes satisfechos",
    statBadge: {
      value: "-45%",
      label: "Tiempo medio de venta",
      sublabel: "con fotografía profesional",
    },
    images: ["/fotos/foto15.jpg", "/fotos/foto6.jpg", "/fotos/foto16.jpg"],
  },
  stats: [
    { value: 500, suffix: "+", label: "Proyectos realizados" },
    { value: 300, suffix: "+", label: "Clientes satisfechos" },
    { value: 8, suffix: " años", label: "De experiencia" },
    { value: 98, suffix: "%", label: "Tasa de repetición" },
  ],
  services: [
    {
      iconName: "Home",
      title: "Fotografía de Interiores",
      desc: "Salones, cocinas, dormitorios y baños capturados con luz natural y técnicas HDR para mostrar cada espacio en su máximo esplendor.",
      detail: "Gran angular · HDR · Retoque profesional",
    },
    {
      iconName: "Camera",
      title: "Fotografía de Fachada",
      desc: "Exteriores del inmueble fotografiados en las mejores condiciones de luz para causar la mejor primera impresión.",
      detail: "Golden hour · Cielos naturales · Alta resolución",
    },
    {
      iconName: "Plane",
      title: "Fotografía Aérea con Dron",
      desc: "Perspectivas únicas desde el aire para viviendas con terreno, urbanizaciones y grandes propiedades.",
      detail: "Dron certificado · Vuelo autorizado · 4K",
    },
    {
      iconName: "Video",
      title: "Video Tour Profesional",
      desc: "Recorrido cinematográfico de la propiedad con edición profesional, música y subtítulos para publicar en cualquier portal.",
      detail: "4K · Edición profesional · Entrega rápida",
    },
    {
      iconName: "Lightbulb",
      title: "Virtual Staging",
      desc: "Amueblamos digitalmente los espacios vacíos para que los compradores visualicen el potencial real de la vivienda.",
      detail: "Renderizado 3D · Varios estilos · 48h",
    },
    {
      iconName: "Layers",
      title: "Pack Completo Inmobiliaria",
      desc: "Fotos, vídeo, plano y virtual tour en un único servicio con precio especial para agencias y promotoras.",
      detail: "Todo incluido · Entrega express · Descuento agencia",
    },
  ],
  gallery: {
    title: "Cada foto cuenta",
    subtitle: "una historia",
    photos: [
      { src: "/fotos/foto1.jpg", alt: "Salón minimalista nórdico", cat: "Salones", span: "col-span-2 row-span-2" },
      { src: "/fotos/foto2.jpg", alt: "Salón dúplex con escalera de cristal", cat: "Salones", span: "" },
      { src: "/fotos/foto3.jpg", alt: "Salón dúplex moderno", cat: "Salones", span: "" },
      { src: "/fotos/foto4.jpg", alt: "Cocina americana open-concept", cat: "Cocinas", span: "col-span-2" },
      { src: "/fotos/foto5.jpg", alt: "Salón en tonos crema con sillones", cat: "Salones", span: "" },
      { src: "/fotos/foto6.jpg", alt: "Cocina-salón con isla de mármol", cat: "Cocinas", span: "" },
      { src: "/fotos/foto7.jpg", alt: "Salón con pared de madera y chimenea", cat: "Salones", span: "col-span-2" },
      { src: "/fotos/foto8.jpg", alt: "Recibidor con mueble nórdico y flores", cat: "Salones", span: "" },
      { src: "/fotos/foto9.jpg", alt: "Baño con orquídeas y ventana", cat: "Baños", span: "" },
      { src: "/fotos/foto10.jpg", alt: "Baño doble lavabo con papel tropical", cat: "Baños", span: "col-span-2 row-span-2" },
      { src: "/fotos/foto11.jpg", alt: "Comedor con terraza al fondo", cat: "Salones", span: "" },
      { src: "/fotos/foto12.jpg", alt: "Baño de mármol con paredes teal", cat: "Baños", span: "" },
      { src: "/fotos/foto13.jpg", alt: "Cocina de madera con suelo espiga", cat: "Cocinas", span: "col-span-2" },
      { src: "/fotos/foto14.jpg", alt: "Salón ático con vigas blancas", cat: "Salones", span: "" },
      { src: "/fotos/foto15.jpg", alt: "Comedor con lámpara dorada y columna", cat: "Salones", span: "" },
      { src: "/fotos/foto16.jpg", alt: "Dormitorio suite con balcón", cat: "Dormitorios", span: "col-span-2" },
      { src: "/fotos/foto17.jpg", alt: "Salón comedor con araña dorada", cat: "Salones", span: "" },
      { src: "/fotos/foto18.jpg", alt: "Salón con estantería de madera", cat: "Salones", span: "" },
      { src: "/fotos/foto19.jpg", alt: "Zona de trabajo con espejo redondo", cat: "Dormitorios", span: "col-span-2" },
      { src: "/fotos/foto20.jpg", alt: "Salón moderno minimalista", cat: "Salones", span: "" },
    ],
    categories: ["Todos", "Salones", "Cocinas", "Baños", "Dormitorios"],
  },
  whyUs: {
    badge: "Por qué elegirnos",
    title: "La diferencia está",
    titleAccent: "en los detalles",
    subtitle:
      "Más de 8 años fotografiando viviendas en toda España nos han enseñado exactamente qué hace que una propiedad destaque sobre las demás.",
    features: [
      { title: "Viviendas que se venden más rápido", desc: "Las propiedades con fotografía profesional reciben hasta un 61% más de visitas online y se venden en la mitad del tiempo." },
      { title: "Equipamiento de gama alta", desc: "Cámara full-frame, objetivos gran angular, flashes de estudio y dron DJI para máxima calidad en cualquier condición de luz." },
      { title: "Entrega en 24-48 horas", desc: "Recibirás todas las imágenes retocadas profesionalmente en 24-48h. Entrega express disponible el mismo día bajo petición." },
      { title: "Garantía de satisfacción", desc: "Si las fotos no superan tus expectativas, repetimos la sesión sin coste adicional. Tu satisfacción es nuestra prioridad absoluta." },
      { title: "Cobertura en toda España", desc: "Disponible en Madrid, Barcelona, Valencia, Sevilla, Málaga y toda la costa. Desplazamiento incluido en zonas metropolitanas." },
      { title: "Retoque profesional incluido", desc: "Corrección de color, enderezado de líneas, eliminación de elementos y optimización para portales inmobiliarios." },
    ],
    statBadge: { value: "+12%", label: "Precio conseguido", sublabel: "sobre el precio de salida" },
    images: ["/fotos/foto13.jpg", "/fotos/foto17.jpg"],
  },
  process: {
    badge: "Proceso",
    title: "Así de",
    titleAccent: "sencillo",
    subtitle: "De tu solicitud a las fotos listas en menos de 48 horas.",
    steps: [
      { title: "Solicita presupuesto", desc: "Cuéntanos el tipo de propiedad, la zona y la fecha. Te enviamos presupuesto en menos de 2 horas sin compromiso." },
      { title: "Sesión fotográfica", desc: "Ignacio se desplaza a la propiedad y realiza la sesión con equipamiento profesional de estudio." },
      { title: "Edición y retoque", desc: "Selección y retoque profesional de cada imagen: color, luz, perspectiva y eliminación de elementos no deseados." },
      { title: "Entrega en 24-48h", desc: "Recibes todas las fotos en alta resolución listas para publicar en Idealista, Fotocasa o tu web inmobiliaria." },
    ],
    stripImages: ["/fotos/foto1.jpg", "/fotos/foto8.jpg", "/fotos/foto12.jpg", "/fotos/foto14.jpg"],
  },
  testimonials: {
    badge: "Testimonios",
    title: "Lo que dicen",
    titleAccent: "nuestros clientes",
    subtitle: "Más de 127 clientes confían en Ignacio de las Rivas para fotografiar sus propiedades.",
    items: [
      { name: "María Fernández", role: "Directora Comercial · ERA Inmobiliaria Madrid", text: "Trabajamos con Ignacio desde hace 3 años. La calidad de sus fotos es incomparable: nuestros pisos se venden entre un 30 y un 40% más rápido que la media del mercado.", rating: 5, initials: "MF" },
      { name: "Carlos Romero", role: "Particular · Venta piso en Salamanca, Madrid", text: "Vendí mi apartamento en 12 días. El agente me dijo que las fotos eran lo que más llamaba la atención en Idealista. Ignacio es un auténtico profesional.", rating: 5, initials: "CR" },
      { name: "Ana Martínez", role: "Promotora Inmobiliaria · Grupo Habitat", text: "Para nuestra nueva promoción de 40 viviendas en Madrid, contamos con Ignacio. El resultado es impresionante. Los pisos piloto quedaron perfectos.", rating: 5, initials: "AM" },
      { name: "Pablo García", role: "Agente Inmobiliario · Engel & Völkers Barcelona", text: "Desde que uso fotografía de Ignacio, el tiempo medio de venta se ha reducido a la mitad. Mis clientes están encantados con los resultados.", rating: 5, initials: "PG" },
      { name: "Lucía Torres", role: "Particular · Venta chalet en La Moraleja", text: "El dron fue un plus increíble. Los compradores llegaban ya enamorados de la propiedad antes de visitarla. Precio conseguido muy por encima del mercado.", rating: 5, initials: "LT" },
      { name: "Roberto Sánchez", role: "Director · RE/MAX España Norte", text: "Usamos a Ignacio para todas nuestras propiedades premium. Su atención al detalle y profesionalidad son simplemente excelentes.", rating: 5, initials: "RS" },
    ],
    ratingValue: "4.9",
    ratingCount: "127",
  },
  contact: {
    badge: "Contacto",
    title: "¿Listo para",
    titleAccent: "destacar tu propiedad?",
    subtitle: "Cuéntanos tu proyecto y te enviamos presupuesto sin compromiso en menos de 2 horas.",
    phone: "601408966",
    email: "info@ignaciodelasfotografia.es",
    location: "Madrid · Disponible en toda España",
    instagram: "@ignaciodelasfotografia",
    whatsapp: "34601408966",
    image: "/fotos/foto11.jpg",
  },
  footer: {
    description: "Fotografía profesional de viviendas en Madrid y toda España. Imágenes que venden más rápido y a mejor precio.",
    services: ["Fotografía de Interiores", "Fotografía de Fachada", "Fotografía con Dron", "Video Tour", "Virtual Staging", "Pack Inmobiliaria"],
    areas: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Málaga", "Costa del Sol", "Toda España"],
    tickerPhotos: ["/fotos/foto1.jpg", "/fotos/foto5.jpg", "/fotos/foto9.jpg", "/fotos/foto13.jpg", "/fotos/foto3.jpg", "/fotos/foto7.jpg", "/fotos/foto11.jpg", "/fotos/foto15.jpg"],
    name: "Ignacio de las Rivas Fotografía Profesional",
    whatsapp: "34601408966",
  },
};
